# -*- coding: utf-8 -*-
"""positive.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18v6QleVOseqd15KeNUo8RbKctPxziUea
"""

start, end = -14,12
for num in range(start, end + 1):

    if num >= 0:
       print(num, end = " ")